# Generated by Django 5.0 on 2025-10-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='CA', max_length=2),
        ),
    ]
